m4/ax_cxx_compile_stdcxx.m4
to avoid
./configure: line 17124: syntax error near unexpected token AX_CXX_COMPILE_STDCXX(14, noext, optional)'
When ./configure
=> Add ax_cxx_compile_stdcxx(.m4) file for build with Ubuntu 16.04

README.rst
(May be also add check if libevent is available because the build fail :
In file included from client.cc:38:0:
client.h:38:16: fatal error: ev.h: No such file or directory
=> Add note about need libevent for build examples

lib/ngtcp2_conn.c, lib/ngtcp2_rtb.c, lib/ngtcp2_rtb.h
Count the number of times a packet has been retransmitted.
At this stage, it's only purpose is to slowly backoff
retransmit timeouts so as not to cause flooding.
In future it could be used for statistics reporting and
telemetry, especially if a similar counter is kept at
the connection level.
Note: a good way to observe retransmit behaviour before
and after this change is to put a gdb breakpoint at
'ngtcp2_conn_recv' in the example client then run the
client and observe the already running server.
=> Add a counter to rtb_entry

examples/client.cc, examples/server.cc
This enables a graceful app exit and in future will allow:
- Closure procedures like CONNECTION_CLOSE on all connections
to be performed
- Full cleanup of allocated memory and resources
=> Add SIGINT handler to example apps

examples/client.cc, examples/client.h, examples/network.h, examples/server.cc, examples/server.h
This patch represents phase 2 of the "Close all
connections on exit" feature, as well as including
a number of other benefits for both client and server:
- Packet writing is now moved to a function: send_packet
this function will sense a number of different errors
on the sendto system call, and categorise these as
either fatal or non fatal (able to be retried).
Non fatal errors will most likely be caused by the
kernel tx queue being full, which means the packet
should be writable at a later time.
This code is loosely based on similar code in the
Berkeley Internet Name Daemon (BIND), which I
assume would know how to send UDP packets.
- Functions that write packets will observe the
send_packet return value and if the network error is
non fatal, the packet that was to be sent will be
queued …
=> Add packet send error checking and retry

.travis.yml
to avoid ./examples/client: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
=> travis: fix rpath

Makefile.am, ci/gen-certificate.sh
At the same time, remove the "gen-certificate" target" since it is not
required as part of the build process and not documented elsewhere. This
script could be used for testing "examples/server".
___
It basically reverts #29 and adds a new script on top. @alagoutte I think you already have modifications to .travis.yml that invoke the test programs, is that correct?
FWIW @alagoutte mentioned that the example programs initially failed to run (fixed by #50) with autotools, but when testing with CMake I found no issues.
=> Simplify test certificate creation

examples/server.cc
generate_reserved_vesrion => generate_reserved_version
=> server (example): fix typo on function name

lib/ngtcp2_rtb.c
Spec 10
```
OnPacketsLost(lost_packets):
// Remove lost packets from bytes_in_flight.
for (lost_packet : lost_packets):
bytes_in_flight -= lost_packet.bytes
largest_lost_packet = lost_packets.last()
// Start a new recovery epoch if the lost packet is larger
// than the end of the previous recovery epoch.
if (!InRecovery(largest_lost_packet.packet_number)):
end_of_recovery = largest_sent_packet
congestion_window *= kLossReductionFactor
congestion_window = max(congestion_window, kMinimumWindow)
ssthresh = congestion_window
```
`end_of_recovery` should be last sent packet number. Otherwise will decrease the congestion window ,which caused by one network jitter, to a low value(decrease too many times).
logs
```
21554 I00001187 0xdbba100dfc696cc4 rcv reduce cwnd because of packet loss …
```
=> Fix the recovery period

examples/CMakeLists.txt, examples/Makefile.am, examples/client.cc, examples/keylog.cc, examples/keylog.h, examples/server.cc
Since draft -13, the exporter secret has become useless for decryption.
While the client and server programs log appropriate secrets using the
"-s" option, let's make integration with Wireshark easier by including
the appropriate labels and identifier (client random).
The corresponding Wireshark patch that uses these secrets:
https://code.wireshark.org/review/29677
(tested with ngtcp2 master (draft -13) and draft-14)
=> examples: Support writing new keylog format

.travis.yml
It is now possible to use Xenial (Ubuntu 16.04) on Travis
Also no longer need to get external clang (on Travis Xenial, it is clang-7)
=> Travis: Update to Xenial

lib/includes/ngtcp2/ngtcp2.h
This commit updates the version in the comment preceding
`NGTCP2_PROTO_VER_D17` to `17` instead of `15`.
=> Update NGTCP2_PROTO_VER_D17 comment to version 17

lib/includes/ngtcp2/ngtcp2.h
This commit attempts to clarify the path parameter to be clear that this
is the path that was validated. Currently this can give the impression
that the callback should validate this path, but my understanding is
that the actual path validation is done by `ngtcp2_pv_validate`.
=> Clarify path parameter in path_validation comment

examples/server.cc
Currently, most of the callbacks that are initialized to nullptr are
commented, apart from two. This commits add the missing comments.
=> Add comments to null callbacks in examples/server

configure.ac, examples/crypto.cc, examples/util.cc
For using in6_addr structure in IPv6 protocl stack  KAME project, add netinet/in.h header in util.cc . And for privent for conflict with bswap64 which defined in OS header, add #ifndef in crypto.cc.
=> modify for FreeBSD

CMakeLists.txt, lib/CMakeLists.txt
- Allow specifying shared or static with BUILD_SHARED_LIBS.
- Add include directories as PUBLIC to library targets.
This enables using ngtcp2 with CMake `add_subdirectory`.
=> CMake improvements.

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Allows retrieving the aead overhead passed with `ngtcp2_conn_set_aead_overhead`.
=> Add `ngtcp2_conn_get_aead_overhead`.

lib/includes/ngtcp2/ngtcp2.h
This allows them to be forward declared. Typedefed anonymous structs
cannot be forward declared without a tag.
=> Add struct tags for structs used in callbacks.

lib/includes/ngtcp2/ngtcp2.h
This commit updates the comment for the addrlen to match the field
name change made in Commit 26440b084538f2c194057681e1031d7030937600 ("Rename len to addrlen").
=> Correct addrlen comment for ngtcp_addr struct

README.rst
This commit removes the `-i, --interactive` option for the client example
which was removed in Commit 9ea17af6ef48281d015a73ce46d6689b2255a037 ("h3 client and server").
=> Remove client -i --interactive option from README

examples/server.cc
This commit updates the `client_hello_cb` to use return values specified
in [SSL_CTX_set_client_hello_cb](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_client_hello_cb.html).
=> Use OpenSSL return values for client_hello_cb

examples/client.cc
This commit updates `write_transport_params` in client.cc to use a
character `'\n'`, instead of string `"\n"`.
=> Use char instead of string for \n in client.cc

examples/client.cc, examples/client.h, examples/server.cc, examples/server.h
A subsequent PR can further simplify `Buffer` as `begin` is now always equal to `head` and `size()` is always equal to `bufsize()`.
=> Remove unused parts of Buffer in example

examples/client.cc
This commit suggests using a closure for the generation of ngtcp2_cids
in Client::init. The motivation for this is to reduce some minor code
duplication.
=> Use closure for scid and dcid generation

lib/includes/ngtcp2/ngtcp2.h
This commit contains a suggestion for improving ngtcp2_recv_crypto_data
documentation.
=> Update ngtcp2_recv_crypto_data documentation

lib/ngtcp2_qlog.c
This commit removes the include of `ngtcp2_macro.h` as it does not seem to
be used.
=> Remove unused ngtcp2_macro include in ngtcp2_qlog

examples/client.cc, examples/client.h, examples/server.cc, examples/server.h
After removing `Buffer::seek`, `head` always equals `begin`. A subsequent diff can further simplify Buffer by removing bufsize(), which is now identical to size().
=> Remove redundant Buffer::head

examples/client.cc
Previously, when mmap() failed the client example crashed deep inside ngtcp2 on trying to access address 0xffffffffffffffff. This can happen for example if `--data` specifies a directory.
=> Check mmap's return value

lib/ngtcp2_gaptr.c, lib/ngtcp2_gaptr.h
The header `ngtcp2_gaptr.h` does not use anything from `ngtcp2_range.h` and
this commit suggests moving the include to `ngtcp2_gaptr.c` instead.
=> Move ngtcp2_range.h into ngtcp2_gaptr.c

examples/client.cc, examples/client.h
This commit moves the include of `template.h` into `client.cc` as it does
not seem to be used any longer by `client.h`.
Commit a7d6c8c44ce5304c4983d0cc276dd2e6b47f3c1c ("Addngtcp2_acked_stream_data_offset callback")
removed the field streambuf_ which was using the user-defined literal `_k` from template.h:
```c
std::array<uint8_t, 32_k> streambuf_;
```
=> Move template.h include to client.cc

lib/ngtcp2_crypto.c
This commit contains a suggestion to add a static function to reduce
some code duplication in `ngtcp2_encode_transport_params`.
=> Add inc_len_varint function to ngtcp2_crypto.c

lib/ngtcp2_conn.c, lib/ngtcp2_conn.h
This commit suggests updating `ngtcp2_conn`'s state field to be of type
`ngtcp2_conn_state` instead of type `int`.
=> Use ngtcp2_conn_state as type for state field

examples/client.cc, examples/server.cc
This commit changes the TLS_method() used by the client and server to
use more specific TLS_client_method() and TLS_server_method().
The main difference between these two are ossl_statem_accept is
undefined for the client, and ossl_statem_connect is undefined for the
server:
```
IMPLEMENT_tls_meth_func(TLS_ANY_VERSION, 0, 0,
TLS_server_method,
ossl_statem_accept,
ssl_undefined_function, TLSv1_2_enc_data)
IMPLEMENT_tls_meth_func(TLS_ANY_VERSION, 0, 0,
TLS_client_method,
ssl_undefined_function,
ossl_statem_connect, TLSv1_2_enc_data)
```
ossl_statem_accept and ossl_statem_connect are defined like this:
```c
int ossl_statem_accept(SSL *s) {
return state_machine(s, 1);
}
int ossl_statem_connect(SSL *s) {
return state_machine(s, 0);
}
```
So they are both calling state_machine but with setting …
=> Use TLS_client_method and TLS_server_method

examples/server.cc
This commit updates the server's `create_ssl_ctx` use `exit(EXIT_FAILURE)`
instead of using a goto label.
The motivation of this is to be consistent with `create_ssl_ctx` in
client.cc.
=> Replace goto in create_ssl_ctx with exit

lib/ngtcp2_crypto.c
This commit adds a static function named put_uint16_varint to reduce
some code duplication when putting some transport parameters.
I was not sure what would be preferred, returning `uint8_t*` like it's currently or making the function void. I'd be happy to change just let me know.
=> Introduce put_uint16_varint function

lib/ngtcp2_conn.c
The code previously determined whether a packet was an Initial packet by looking at its type value, without first checking it was not a Version Negotiation packet. In the case of a Version Negotiation packet, reading the type value returned the random value in the Unused field. This occasionally caused Version Negotiation packets to be misinterpreted as Initial packets. When this happened, ngtcp2_conn_read_pkt() returned NGTCP2_ERR_DRAINING instead of NGTCP2_ERR_RECV_VERSION_NEGOTIATION.
=> Fix condition checking for Initial packet

CMakeLists.txt
When using `CMake` to build ngtcp2, the definition of `ssize_t` is incorrect for 64-bit builds. It's defined as an `int`, which at least on Windows is a 32-bit type.
What this means is that any ngtcp2 function that returns an error code ends up returning a bit pattern that, on 64-bit builds, is interpreted by the caller as a _large positive number_ instead of a _small negative number_. That's because the caller (e.g. libcurl) will probably have a different definition of `ssize_t`, one that is correctly sized as a signed 64-bit integer, not a signed 32-bit integer.
Here's an example of the assembly code currently generated for ngtcp2 on 64-bit Windows for `conn_write_pkt`:
```
return NGTCP2_ERR_WRITE_STREAM_MORE;
00007FF76790FEBE  mov         eax,0FFFFFF10h  
```
That instruction is only …
=> Fix definition of ssize_t in CMake for 64-bit builds

tests/ngtcp2_test_helper.c
write_single_frame_pkt() returns a packet length greater than the number of bytes it writes to the buffer. The returned length reflects a fake AEAD overhead, while this extra overhead is never written. As a result, ngtcp2_verify_stateless_reset_token() uses initialized data when reading the end of the packet. This causes noise when using a memory sanitizer.
=> Fix use of uninitialized data in tests

lib/ngtcp2_conn.c
conn_rotate_keys() frees conn->pktns->crypto.tx.ckm. If there is a pending ppe, the ppe object still holds a reference to the freed memory and will eventually try to use it in ngtcp2_ppe_final().
=> Avoid use-after-free if key update is initiated while ppe is pending

examples/server.cc
Handler::wev_ is initialized with a file descriptor set to 0. ev_io_set() is never called for this watcher, so its file descriptor remains 0 and all calls to ev_io_start() have no effect. As a result writecb() is never called.
There may still be an issue due to all endpoints sharing the same watcher, but this is mostly orthogonal to the problem fixed here.
=> Fix example server's write callback never being called

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_pkt.c
These two input buffers are not modified as part of the function
and can/should thus be `const`.
=> Make ngtcp2_pkt_write_stateless_reset use const for input

crypto/shared.c
The call to `ngtcp2_crypto_set_remote_transport_params()` must come before the call to `ngtcp2_conn_install_key()`
Fixes: https://github.com/ngtcp2/ngtcp2/issues/213
=> Fix setting remote transport params order

examples/client.cc, examples/client.h
It always equals to buf.data().
=> Remove redundant Buffer::begin

lib/ngtcp2_conn.c
Sometimes the ACK to 0-RTT packet is coalesced with other short header packet. In ngtcp2_conn_writev_stream, if server has not received ClientFinish, it will invoke ngtcp2_conn_write_handshake. And inside that function, it tries to write ACK to 0-RTT packet as pure ACK packet. After returning from ngtcp2_conn_write_handshake, writev_stream can write more stream data as another QUIC packet. These 2 QUIC packets will then be coalesced into one UDP packet.
Removing this 2 blocks seems working, as ngtcp2_conn_writev_stream will also check if ACK needs to be written. It'll then contain the ACK frame in the following short header packet (previously coalesced with) instead of having ACK as a separate QUIC packet.
=> Fix coalesced 0-RTT ACK packet with short header packet

examples/client.cc, examples/server.cc
The return value from this function is not used.
=> Simplify remove_tx_stream_data()

lib/ngtcp2_log.c
ngtcp2_connection_close.reason_len is size_t, which is not necessarily 64-bit.
=> Fix format specifier in log_fr_connection_close()

lib/ngtcp2_log.c
Commit 0999d327a1511acdc3fed93d2c6d040b5256dbad ("Pass user-defined printf function rather than passing file descriptor") removed the usage of errno so it does not need to be included.
=> Remove unused errno.h include from ngtcp2_log

lib/ngtcp2_conn.c
This causes conn_get_earliest_pktns() to falsely report a nonzero loss time, resulting in spurious retransmissions.
=> Fix integer wraparound on 32-bit machines

lib/ngtcp2_crypto.c
If `valuelen` is 0 and `p` equals `end`, `decode_varint_param()` reads an extra byte past the end of the buffer.
=> Fix read-heap-buffer-overflow in decode_varint_param()

CMakeLists.txt, CMakeOptions.txt, crypto/gnutls/CMakeLists.txt, crypto/openssl/CMakeLists.txt, lib/CMakeLists.txt
A functional fix and a documentation fix:
* CMake: ensure libs are built position-independent
Static libraries have to be built as position-independent, otherwise
they cannot be linked into a shared library which is built
position-independent (-fPIC).
Without this, linking objects into libcurl.so fails with:
/usr/bin/ld: libngtcp2.a(ngtcp2_conn.c.o): relocation R_X86_64_PC32 against symbol `__asan_option_detect_stack_use_after_return' can not be used when making a shared object; recompile with -fPIC
* CMake: add BUILD_SHARED_LIBS option
Prior to commit 4e955731d3a6ac344a593ee9d9c5d00982846adf, ngtcp2 was
built as shared library. That has changed into a static or shared
library depending on the BUILD_SHARED_LIBS option, but this option was
not documented and the comments were misleading. …
=> Fix static library builds, clarify shared libs situation

lib/ngtcp2_conn.c
This is unlikely to wraparound in the real world, but fixing it makes the code easier to fuzz.
=> Fix potential wraparound in conn_update_recv_rate()

lib/ngtcp2_crypto.c
Node.js makes the full `ngtcp2_transport_params` struct available
for storage as a byte array, including any possible padding
in the struct.
Fully initializing the struct with `memset()` makes this deterministic.
=> Fully initialize ngtcp2_transport_params

lib/ngtcp2_cc.c
`ngtcp2_cc.c` is using the `__builtin_clzll` intrinsic which doesn't exist on MSVC. Added the use of the corresponding [`__lzcnt` intrinsics](https://docs.microsoft.com/en-us/cpp/intrinsics/lzcnt16-lzcnt-lzcnt64?view=vs-2019) for MSVC.
=> Fix MSVC build

lib/ngtcp2_conv.c, lib/ngtcp2_conv.h
`ngtcp2` defines its own version of the `htonl` functions on Windows in order to avoid having to link against `ws2_32.lib`. However, the way it defines these functions conflicts with the declarations on the Windows headers, causing build errors on 32-bit Windows builds:
```
$ cmake -G "Visual Studio 16 2019" -A Win32 ..
-- Selecting Windows SDK version 10.0.20180.0 to target Windows 10.0.20190.
-- The C compiler identification is MSVC 19.28.29115.0
-- The CXX compiler identification is MSVC 19.28.29115.0
...
-- Configuring done
-- Generating done
-- Build files have been written to: _build
$ cmake --build .
...
lib\ngtcp2_conv.h(85,15): error C2373: 'htonl': redefinition; different type modifiers [_build\lib\
ngtcp2.vcxproj]
C:\Program Files (x86)\Windows …
```
=> Fix Windows build

lib/ngtcp2_conn.c
There is a small typo in lib/ngtcp2_conn.c.
Should read `exceeds` rather than `excceds`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, excceds -> exceeds

lib/ngtcp2_conn.h
ngtcp2_mem.h was included twice in ngtcp2_conn.h. Removing one.
=> Remove double include of ngtcp2_mem.h from ngtcp2_conn.h

examples/tls_client_context_openssl.cc, examples/tls_server_context_openssl.cc
On Fedora 34 I am seeing this compile error:
```
tls_server_context_openssl.cc: In member function ‘int TLSServerContext::init(const char*, const char*, ngtcp2::AppProtocol)’:
tls_server_context_openssl.cc:315:45: error: ‘numeric_limits’ is not a member of ‘std’
315 |   SSL_CTX_set_max_early_data(ssl_ctx_, std::numeric_limits<uint32_t>::max());
|                                             ^~~~~~~~~~~~~~
```
=> including limits for std::numeric_limits

lib/includes/ngtcp2/ngtcp2.h
I was trying to write a small program using `NGTCP2_WRITE_STREAM_FLAG_MORE`, and stumbled on how to stop the loop if there is no data to be fed. Hopefully this makes it a little clearer.
=> doc: Clarify NGTCP2_WRITE_STREAM_FLAG_MORE behavior on how to stop coalescing

lib/ngtcp2_conn.c
The NGTCP2_PV_FLAG_DONT_CARE path validation is there to return to the old path in case of fradulent migration (it would be cleaner if this would run in parallel with the path validation triggered by migration, but that would require parallel path validations, cough cough cough :) ); we should not report it's result via callback
=> we do not care about result of this path validation

lib/ngtcp2_pkt.c
The value returned from ngtcp2_pkt_decode_datagram_frame() is later returned from ngtcp2_pkt_decode_frame(). According to its contract, ngtcp2_pkt_decode_frame() returns NGTCP2_ERR_FRAME_ENCODING when the payload is too short.
=> Fix incorrect return value from ngtcp2_pkt_decode_datagram_frame()

lib/includes/ngtcp2/ngtcp2.h
This is an additional fix for https://github.com/ngtcp2/ngtcp2/issues/337, but this one for MSVC.
----
Microsoft introduced the C5029 warning with Visual Studio 2015. This warning only applies to C++ mode, but it does not seem to be language specific (i.e. ngtcp2 will trigger it when included from C++, even if it is within an extern C block). Basically, C5029 will be raised when an alignment specified is added to an alias and not the original type, because this is a non-standard extension (see [this page](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999?view=msvc-170)).
```
typedef __declspec(align(8)) struct ngtcp2_pkt_info {
// ...
} ngtcp2_pkt_info;
```
In the code you had previously, the `ngtcp2_pkt_info` structure was aligned …
=> Fix the non-standard alignment specifier for C++

crypto/gnutls/gnutls.c
Ignore non-fatal errors from gnutls_handshake_write.  Send alert on
fatal error.
=> gnutls: Ignore non-fatal errors from gnutls_handshake_write

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h
Ensure that QUIC handshake completion is declared after 1RTT keys are
installed.  It looks like some TLS implementations declare TLS
handshake completion early (e.g., when server sends Server Finished)
and before installing 1RTT rx key.  While it might be OK for TLS, we
need 1RTT keys in tact when QUIC handshake is completed.  This commit
adds an explicit requirement for the availability of 1RTT keys when
the library declares QUIC handshake completion.
=> Declare QUIC handshake completion after 1RTT keys are installed

lib/ngtcp2_conn.c
There was an unintentional use of ssize_t, so I fixed it to use ngtcp2_ssize.
=> Use ngtcp2_ssize instead of ssize_t

configure.ac
Prior to this change OpenSSL >= 1.1.1 without QUIC was not properly
disabled. make would attempt to build libngtcp2_crypto_openssl anyway
and fail.
Bug: https://github.com/curl/curl/pull/8485
Reported-by: Michał Antoniak
Closes #xxxx
=> configure.ac: fix have_openssl_quic detection

examples/client.cc, examples/h09client.cc, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_rtb.c
This change fixes the bug that a packet which elicits key update
confirmation from the remote endpoint might not be sent.  This might
lead to connection failure if the remote endpoint keeps changing keys
very frequently.  Changing keys in this frequency is unusual, but it
is allowed by the spec, and we should deal with it.
=> Make sure that a packet which elicits key update confirmation is sent

lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_rtb.c, tests/ngtcp2_conn_test.c
If key update is initiated by a remote endpoint, acknowledging a
packet encrypted by the new key completes key update.
=> Key update is confirmed by acknowledging a packet encrypted by new key

CMakeLists.txt
In MSVC the regex replace of compiler flags for a release build caused some flags to be fused together, `/Gy/Z7`, which resulted in the following error.
`cl : Command line error D8016 : '/O2' and '/GZ' command-line options are incompatible`
Took the same section from nghttp2's CMakeLists which contains a space to fix the issue.
=> Fix regex replace of compiler flags

examples/client.cc, examples/client_base.cc, examples/client_base.h, examples/h09client.cc, examples/h09server.cc, examples/server.cc, examples/server_base.cc, examples/server_base.h, examples/shared.cc, examples/shared.h, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
ngtcp2_conn_write_connection_close2 is introduced, which replaces
ngtcp2_conn_write_connection_close and
ngtcp2_conn_write_application_close.
ngtcp2_conn_write_connection_close and
ngtcp2_conn_write_application_close are now deprecated, and removed in
the next release.  ngtcp2_conn_write_connection_close2 will be renamed
to ngtcp2_conn_write_connection_close.
Added helper functions to fill ngtcp2_connection_close_error object
for various types of errors.  In general, QUIC has 2 error code type:
transport and application.  ngtcp2 has 2 special subtypes of transport
error code type.  One indicates version negotiation and the other
indicates idle close.  These types should be recognized because we do
not send CONNECTION_CLOSE on these events.
=> Rework error handling

doc/source/programmers-guide.rst, examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_pkt.c, lib/ngtcp2_pkt.h, tests/ngtcp2_conn_test.c, tests/ngtcp2_pkt_test.c, tests/ngtcp2_test_helper.c
Now ngtcp2_accept does not return NGTCP2_ERR_VERSION_NEGOTIATION.  It
should be handled by inspecting the return value of
ngtcp2_pkt_decode_version_cid.
=> Make NGTCP2_PKT_* type QUIC version independent

.github/workflows/build.yml, doc/source/programmers-guide.rst, examples/client.cc, examples/client_base.h, examples/h09client.cc, examples/h09server.cc, examples/server.cc, examples/server_base.h, examples/shared.cc, examples/shared.h, lib/CMakeLists.txt, lib/Makefile.am, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_pmtud.c, lib/ngtcp2_pmtud.h, lib/ngtcp2_rtb.c, lib/ngtcp2_rtb.h, tests/CMakeLists.txt, tests/Makefile.am, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_pmtud_test.c, tests/ngtcp2_pmtud_test.h
This adds simple Path MTU Discovery mechanism, which probes predefined
size of path MTU.  ngtcp2_settings.assume_symmetric_path is removed in
favor of Path MTU Discovery.  This commits also other datagram size
enforcements and fixes like limiting a packet containing
PATH_CHALLENGE/PATH_RESPONSE frames to unvalidated path to 1200.
ngtcp2_conn_get_path_max_udp_payload_size is replaced with
ngtcp2_conn_get_max_udp_payload_size because it is unknown in advance
that ngtcp2_conn_writev_* writes to which path.
=> Simple Path MTU Discovery

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_pmtud.c, lib/ngtcp2_pmtud.h, tests/ngtcp2_pmtud_test.c
Limit PMTUD probe size to ngtcp2_settings.max_udp_payload_size.  To
make PMTUD work with the default value, set 1452 to
ngtcp2_settings.max_udp_payload_size.  max_udp_payload_size per path
is still limited to 1200.
=> Limit PMTUD probe size to ngtcp2_settings.max_udp_payload_size

doc/source/programmers-guide.rst, examples/client.cc, examples/client.h, examples/gtlssimpleclient.c, examples/h09client.cc, examples/h09client.h, examples/h09server.cc, examples/h09server.h, examples/server.cc, examples/server.h, examples/simpleclient.c, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_err.c, tests/ngtcp2_conn_test.c
Merge expiry from ngtcp2_conn_get_idle_expiry into
ngtcp2_conn_get_expiry, and let ngtcp2_conn_handle_expiry deal with
idle timeout.  On idle timeout, ngtcp2_conn_handle_expiry returns
NGTCP2_ERR_IDLE_CLOSE.  ngtcp2_conn_get_idle_expiry is removed from
the public API surface.
ngtcp2_connection_close_error_set_transport_error_idle_close is
removed in favor of passing NGTCP2_ERR_IDLE_CLOSE to
ngtcp2_connection_close_error_set_transport_error_liberr.
Now ngtcp2_conn_write_connection_close returns 0 if a connection
object is in closing or draining period instead of returning
NGTCP2_ERR_INVALID_STATE.
=> Unified timer

examples/h09server.cc, examples/server.cc
Fix bug in #401 which causes invalid GSO packet if it sees larger
packet than current gso_size.
=> Amend #401

examples/client.cc, examples/h09client.cc
Avoid SO_REUSEADDR on client side which allows bind to assign the same
port multiple times if it is not an active listening port.
=> Avoid SO_REUSEADDR on client side

lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_rtb.c, lib/ngtcp2_rtb.h
Fix the bug which causes dead lock on low cwnd situation.  This is
caused by lost PATH_CHALLENGE/PATH_RESPONSE or PMTUD probe packets,
which do not trigger PTO probe packets.
=> Fix dead lock on low cwnd

crypto/shared.c, examples/tls_server_context_boringssl.cc, examples/tls_server_context_openssl.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, tests/ngtcp2_conn_test.c
client chosen version is a new concept introduced by QUIC Version
Negotiation Draft-07.  Since the current code in ngtcp2 only supports
compatible negotiation inside a single connection attempt, client
chosen version is more suitable than original version.
=> Rename original_version to client_chosen_version

examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
This commit makes server other_versions default to v1.  server VN is
adjusted to reflect this and now it sends only v1 (+ a reserved
version) in VN.  The side effect of this change is that we cannot
specify empty other_versions field.  But since other_versions cannot
be empty on incompatible version negotiation, we almost always need
non-empty server other_versions.
=> Server other_versions defaults to v1

lib/ngtcp2_conn.c
Send PMTUD when there is no Handshake CRYPTO to send in order not to
interfere multi-packet Handshake messages from client(e.g., client
certificate).  Saving CWND for Handshake CRYPTO is also nice in early
phase of the connection.
=> Send PMTUD when there is no Handshake CRYPTO to send

lib/ngtcp2_bbr2.c
If loss happens before pipe is filled, bbr2 congestion controller
prematurely declares filled pipe event which significantly
underestimates the available bandwidth.
=> bbr2: Ignore congestion event before filling pipe

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Nullify QUIC transport parameters version_info when set because they
could contain dangling pointers, and they are not used after that at
the moment.
=> Nullify QUIC transport parameters version_info when set

crypto/boringssl/boringssl.c, crypto/openssl/openssl.c, crypto/shared.c, examples/tls_client_session_gnutls.cc, examples/tls_client_session_picotls.cc, examples/tls_server_context_picotls.cc, examples/tls_server_session_gnutls.cc, examples/tls_server_session_picotls.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Add functions to encode or decode transport parameters from or to
ngtcp2_conn directly.
=> Add functions to encode/decode transport parameters directly

examples/client.cc, examples/client_base.cc, examples/h09client.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_crypto.c, lib/ngtcp2_crypto.h, lib/ngtcp2_rtb.c, tests/ngtcp2_conn_test.c
Allocate remote transport parameters dynamically in order to retain all
fields.
=> Allocate remote transport parameters dynamically

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h
Hide ngtcp2_conn_set_remote_transport_params in favor of
ngtcp2_conn_decode_remote_transport_params.
=> Hide ngtcp2_conn_set_remote_transport_params

examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Make ngtcp2_conn_get_local_transport_params return a pointer to the
stored object.
=> Make ngtcp2_conn_get_local_transport_params return pointer

examples/tls_client_context_boringssl.cc, examples/tls_client_context_openssl.cc
Since TLS session has been stored externally, I feel that there is no need to enable session caching in OpenSSL and BoringSSL, just like [what Google QUICHE does](https://github.com/google/quiche/blob/74aa2867de8e650809d85cd6454aca4200ec6e36/quiche/quic/core/crypto/tls_client_connection.cc#L24-L27).
=> Disable the internal session cache if TLS session is stored externally

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_crypto.c, tests/ngtcp2_crypto_test.c
By passing dest = NULL and destlen = 0, now
ngtcp2_encode_transport_params just returns the number of bytes
required to store the encoded transport parameters.
=> Return the number of bytes required to store an encoded TP

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
If STOP_SENDING is sent, either wait for RESET_STREAM or ACKs that
acknowledge all STREAM data up to fin.
We do not wait for ACK for RESET_STREAM if all tx data have been
acknowledged.
=> Tweak condition of stream closure

crypto/boringssl/boringssl.c, crypto/picotls/picotls.c, examples/client.cc, examples/h09client.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
ngtcp2_conn_early_data_rejected() always returns 0.
=> Remove return value from ngtcp2_conn_early_data_rejected()

examples/client.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Do not return NGTCP2_ERR_STREAM_NOT_FOUND from the following
functions:
- ngtcp2_conn_shutdown_stream
- ngtcp2_conn_shutdown_stream_write
- ngtcp2_conn_shutdown_stream_read
- ngtcp2_conn_extend_max_stream_offset
and returns 0 if a stream is not found.
The reason is that it is too tedious to check
NGTCP2_ERR_STREAM_NOT_FOUND in every invocation for these functions.
In almost all cases, if NGTCP2_ERR_STREAM_NOT_FOUND is returned, we
just simply ignores it and pretend that the function succeeds.
=> Do not return NGTCP2_ERR_STREAM_NOT_FOUND

interop/run_endpoint.sh
Disable PMTUD for ecn test case because ngtcp2 does not set ECN bit
for PMTUD packets.
=> interop: Disable PMTUD for ecn test case

lib/ngtcp2_conn.c, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conn_test.h
ngtcp2_conn.c:3071: uint64_t dcid_tx_left(ngtcp2_dcid *): Assertion
`dcid->bytes_recv * 3 >= dcid->bytes_sent' failed.
This happened because 1RTT ACK only frame is sent without
amplification limit.
=> Fix assertion failure due to amplification limit violation

README.rst
wolfSSL 5.5.0 ships the previously shown commit ID, which adds QUIC/ngtcp2 support.
=> Update README with wolfSSL version number

.github/workflows/build.yml, ci/build_openssl3.sh
Specify --openssldir to the system path in order to avoid 'unregistered scheme' error when receiving client certificate, which is a yet another regression introduced in OpenSSL v3.
=> workflow: Run examples/tests

lib/ngtcp2_conn.c
Client also validates server source address on successful Handshake packet processing.
=> Fix client side address validation

examples/Makefile.am
BoringSSL needs to be compiled with ASAN if ngtcp2 is built with ASAN, otherwise bsslclient and bsslserver will crash if jemalloc is linked.
=> autotools: Use jemalloc for all clients and servers

crypto/boringssl/boringssl.c, crypto/picotls/picotls.c, examples/client.cc, examples/client.h, examples/gtlssimpleclient.c, examples/h09client.cc, examples/h09client.h, examples/simpleclient.c, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Add ngtcp2_early_data_rejected callback in order to handle the situation that client decided not to attempt early data before sending its first flight.
=> Add ngtcp2_early_data_rejected callback

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc
Simplify max_pktcnt computation now that all CCs enable pacing.
=> Simplify max_pktcnt computation

doc/source/programmers-guide.rst, examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_bbr.c, lib/ngtcp2_bbr2.c, lib/ngtcp2_cc.c, lib/ngtcp2_conn.c, lib/ngtcp2_rtb.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_rtb_test.c
Rename max_udp_payload_size for tx to max_tx_udp_payload_size to disambiguate it from the rx counterpart.
=> Rename max_udp_payload_size for tx to max_tx_udp_payload_size

lib/includes/ngtcp2/ngtcp2.h
Improve ngtcp2_conn_writev_stream documentation with NGTCP2_WRITE_STREAM_FLAG_MORE to include all possible error codes which allow an application to continue.
=> Improve ngtcp2_conn_writev_stream doc with NGTCP2_WRITE_STREAM_FLAG_MORE

lib/ngtcp2_conv.c, lib/ngtcp2_conv.h, lib/ngtcp2_crypto.c, lib/ngtcp2_pkt.c, lib/ngtcp2_ppe.c, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conv_test.c, tests/ngtcp2_conv_test.h, tests/ngtcp2_crypto_test.c, tests/ngtcp2_pkt_test.c
Rename ngtcp2_get_varint_len and ngtcp2_put_varint_len to ngtcp2_get_varintlen and ngtcp2_put_varintlen respectively.
=> Rename ngtcp2_get_varint_len and ngtcp2_put_varint_len

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_log.c, lib/ngtcp2_pkt.c, lib/ngtcp2_pkt.h, lib/ngtcp2_ppe.c, lib/ngtcp2_qlog.c, lib/ngtcp2_rtb.c, lib/ngtcp2_rtb.h, tests/ngtcp2_conn_test.c, tests/ngtcp2_pkt_test.c, tests/ngtcp2_test_helper.c
Previously, tokens are of type ngtcp2_vec.  Meanwhile, in other places, we use a pair of plain pointer to const uint8_t and size_t as length.  This commit changes the type of tokens to a pair of pointer and size_t for consistency.
=> Make token a pair of pointer to const uint8_t and its size

crypto/boringssl/CMakeLists.txt, crypto/gnutls/CMakeLists.txt, crypto/openssl/CMakeLists.txt, crypto/picotls/CMakeLists.txt, crypto/wolfssl/CMakeLists.txt, lib/CMakeLists.txt
Add `STATIC_LIB_SUFFIX` to set the suffix directly.
This follows the same behavior as nghttp2 and nghttp3.
=> Make hard-coded static library suffix optional

crypto/shared.c, crypto/shared.h, examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc, examples/tls_server_context_boringssl.cc, examples/tls_server_context_openssl.cc, examples/tls_server_context_wolfssl.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_pkt.c, tests/ngtcp2_test_helper.c
Remove QUIC version 2 draft because QUIC version 2 draft most likely requires old Version Information transport parameter codepoint, which ngtcp2 does not support anymore.
=> Remove QUIC version 2 draft

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Remove the default handshake timeout because the current value (10 seconds) is arbitrary choice and no good reason behind it.
=> Remove the default handshake timeout

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Send 2 Handshake probe packets to avoid expensive consecutive PTOs.
=> Send 2 Handshake probe packets

lib/Makefile.am, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_bbr.c, lib/ngtcp2_bbr.h, lib/ngtcp2_bbr2.c, lib/ngtcp2_cc.c, lib/ngtcp2_cc.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_conn_stat.h, lib/ngtcp2_qlog.c, lib/ngtcp2_rst.c, lib/ngtcp2_rst.h, lib/ngtcp2_rtb.h
ngtcp2_conn_stat includes internal data structure and not suitable for public use.  We will provide some kind of connection information like struct tcp_info at some point, but it will be something different from ngtcp2_conn_stat.
=> Hide ngtcp2_conn_stat from public API set

interop/run_endpoint.sh
Set initial rtt to 100ms in interop script to deal with super high packet loss rate.
=> interop: Set initial rtt to 100ms

lib/ngtcp2_conn.c, lib/ngtcp2_pv.h, tests/ngtcp2_conn_test.c
NGTCP2_PV_FLAG_MTU_PROBE was introduced to deal with the second path validation due to amplification limit.  If the path validation with that flag failed, ngtcp2 returns NGTCP2_ERR_NO_VIALBE_PATH.  But we have always the fallback path when this second path validation is performed.  We can just fallback to the old path when the 2nd validation failed, which removes the need to return NGTCP2_ERR_NO_VIALBE_PATH and NGTCP2_PV_FLAG_MTU_PROBE flag.
=> Remove NGTCP2_PV_FLAG_MTU_PROBE

crypto/shared.c, crypto/shared.h
There was only "quicv2 ku" HKDF label which was missing.
=> Make the key update feature be supported by QUIC v2.

.github/workflows/build.yml
Fix nghttp3 cache key race between matrix jobs.  Add missing fail-on-cache-miss: true to nghttp3 cache restore step.  Add --with-libnghttp3 to configure so that it fails if libnghttp3 is missing.
=> Fix nghttp3 cache key race

lib/ngtcp2_ringbuf.c
When building on Windows with clang for ARM targets, `__popcnt` is defined.
=> Clang has __popcnt for ARM

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc
Do no start wev watcher when pacing timer is set.
There are still 2 cases that wev watcher is explicitly enabled:
- when signaling write event
- UDP write is blocked
Fixes #693
=> Do no start wev watcher when pacing timer is set

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_addr.h, lib/ngtcp2_conn.c
Add old_path parameter to ngtcp2_path_validation to allow server to send NEW_TOKEN if a remote address changes.
=> Add old_path parameter to ngtcp2_path_validation

doc/source/programmers-guide.rst, examples/h09server.cc, examples/server.cc, examples/tls_server_session_boringssl.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_crypto.c, lib/ngtcp2_log.c, lib/ngtcp2_log.h, tests/ngtcp2_conn_test.c, tests/ngtcp2_crypto_test.c
ngtcp2_transport_params.original_dcid_present and initial_scid_present have been added and they indicate the presence of original_dcid and initial_scid respectively.
server explicitly now has to set
ngtcp2_transport_params.original_dcid_present to nonzero when setting original_dcid.
ngtcp2_transport_params_type and NGTCP2_TRANSPORT_PARAMS_DECODE_FLAGs have been removed.
ngtcp2_decode_transport_params now does not return NGTCP2_ERR_REQUIRED_TRANSPORT_PARAM.  Caller should check original_dcid_present and initial_scid_present instead.
ngtcp2_decode_transport_params now does not fail if it decodes client written transport parameters and it finds parameters that are not allowed for client to produce.  Caller should check original_dcid_present, stateless_reset_token_present, …
=> Rework transport parameters

examples/client.cc
Fix bug that nghttp3_conn is not initialized when resuming session without sending early data.
=> client: Fix bug that nghttp3_conn is not initialized

examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Add NGTCP2_PATH_VALIDATION_FLAG_NEW_TOKEN to indicate that server should send NEW_TOKEN for the new remote address.
=> Add NGTCP2_PATH_VALIDATION_FLAG_NEW_TOKEN

interop/run_endpoint.sh
interop zerortt test fails if client sends any data (it counts literary QUIC packet payload size, not just STREAM frame) more than 0.5 * file name length * the number of files.  Sending client PMTUD packets exceeds this threshold.
=> interop: Disable PMTUD for zerortt test

lib/includes/ngtcp2/ngtcp2.h
Use uint8_t for bool fields to potentially reduce space as we do in ngtcp2_transport_params.
=> Use uint8_t for bool fields

examples/client.cc, examples/client_base.cc, examples/client_base.h, examples/gtlssimpleclient.c, examples/h09client.cc, examples/h09server.cc, examples/server.cc, examples/server_base.cc, examples/server_base.h, examples/simpleclient.c, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conn_test.h
- ngtcp2_connection_close_error_code_type -> ngtcp2_ccerr_code_type
- NGTCP2_CONNECTION_CLOSE_ERROR_CODE_* -> NGTCP2_CCERR_CODE_TYPE_*
- ngtcp2_connection_close_error -> ngtcp2_ccerr
- ngtcp2_connection_close_error_default -> ngtcp2_ccerr_default
- ngtcp2_connection_close_error_set_transport_error -> ngtcp2_ccerr_set_transport_error
- ngtcp2_connection_close_error_set_transport_error_liberr -> ngtcp2_ccerr_set_liberr
- ngtcp2_connection_close_error_set_transport_error_tls_alert -> ngtcp2_ccerr_set_tls_alert
- ngtcp2_connection_close_error_set_application_error -> ngtcp2_ccerr_set_application_error
- ngtcp2_conn_get_connection_close_error -> ngtcp2_conn_get_ccerr
=> Shorten long names related to connection_close_error

examples/client.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Remove ngtcp2_conn_get_max_local_streams_uni.  The only use case for this function is fulfilled by ngtcp2_conn_get_streams_uni_left. ngtcp2_conn_get_max_local_streams_uni is actually hard to use because caller needs to remember the number of the opened streams.
=> Remove ngtcp2_conn_get_max_local_streams_uni

lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conn_test.h, tests/ngtcp2_gaptr_test.c, tests/ngtcp2_gaptr_test.h
This change adds tests for ngtcp2_conn_create_ack_frame.  With these tests, we identified and fixed the following bugs:
- The invalid ACK frame is generated if the largest packet number in ngtcp2_acktr is the largest acked packet number minus 1.
- The conditions of immediate acknowledgement are updated to follow the RFC.  See https://datatracker.ietf.org/doc/html/rfc9000#section-13.2.1
Fixes #773
=> Add tests for ngtcp2_conn_create_ack_frame

examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Remove odcid from ngtcp2_qlog_settings.  group_id is deduced from local ngtcp2_transport_params if a local endpoint is server.
=> Remove odcid from ngtcp2_qlog_settings

crypto/boringssl/boringssl.c, crypto/gnutls/gnutls.c, crypto/includes/ngtcp2/ngtcp2_crypto.h, crypto/includes/ngtcp2/ngtcp2_crypto_boringssl.h, crypto/includes/ngtcp2/ngtcp2_crypto_gnutls.h, crypto/includes/ngtcp2/ngtcp2_crypto_openssl.h, crypto/includes/ngtcp2/ngtcp2_crypto_picotls.h, crypto/includes/ngtcp2/ngtcp2_crypto_wolfssl.h, crypto/openssl/openssl.c, crypto/picotls/picotls.c, crypto/shared.c, crypto/wolfssl/wolfssl.c, examples/client.cc, examples/debug.cc, examples/debug.h, examples/h09client.cc, examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Rename ngtcp2_crypto_level to ngtcp2_encryption_level.  This commit also renames the following names:
- NGTCP2_CRYPTO_LEVEL_INITIAL -> NGTCP2_ENCRYPTION_LEVEL_INITIAL
- NGTCP2_CRYPTO_LEVEL_HANDSHAKE -> NGTCP2_ENCRYPTION_LEVEL_HANDSHAKE
- NGTCP2_CRYPTO_LEVEL_APPLICATION -> NGTCP2_ENCRYPTION_LEVEL_1RTT
- NGTCP2_CRYPTO_LEVEL_EARLY -> NGTCP2_ENCRYPTION_LEVEL_0RTT
=> Rename ngtcp2_crypto_level to ngtcp2_encryption_level

crypto/shared.c, doc/source/programmers-guide.rst, examples/client.cc, examples/h09client.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conn_test.h
Rename early functions to 0rtt except for those that are specifically related to TLSv1.3 early data (e.g., ngtcp2_early_data_rejected)
=> Rename early functions to 0rtt

examples/client.cc, examples/gtlssimpleclient.c, examples/h09client.cc, examples/h09server.cc, examples/server.cc, examples/simpleclient.c, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Rename the following functions:
- ngtcp2_conn_is_in_closing_period -> ngtcp2_conn_in_closing_period
- ngtcp2_conn_is_in_draining_period -> ngtcp2_conn_in_draining_period
=> Rename ngtcp2_conn_is_in_closing_period and ngtcp2_conn_is_in_draining_period

lib/ngtcp2_net.h
Use _byteswap_uint64 for win32.
=> Only define ngtcp2_bswap64 for little endian platform

crypto/includes/ngtcp2/ngtcp2_crypto.h, crypto/includes/ngtcp2/ngtcp2_crypto_picotls.h, crypto/shared.c, crypto/shared.h, lib/includes/ngtcp2/ngtcp2.h
Update documentation.
Hide following macros/enums/functions:
macros
- NGTCP2_CRYPTO_INITIAL_SECRETLEN
- NGTCP2_CRYPTO_INITIAL_KEYLEN
- NGTCP2_CRYPTO_INITIAL_IVLEN
function
- ngtcp2_crypto_hkdf_expand_label
enum
- ngtcp2_crypto_side
=> Tweak crypto helper library API

examples/client.cc, examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Add flags to ngtcp2_conn_shutdown_stream functions as an extension point.
=> Add flags to ngtcp2_conn_shutdown_stream

README.rst, configure.ac
Older versions do not work because of the bug that cannot deal with partially received TLS messages correctly.
Minimum version in configure script is set to 3.7.3 because that is the GnuTLS version ubuntu 22.04 has.
=> Require GnuTLS >= 3.7.5

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
This changes the default value of keep-alive timeout to UINT64_MAX. Previously, it is 0, and it is the value that disables keep-alive. Now, to disable keep-alive, set it to UINT64_MAX.
=> keep-alive timeout defaults to UINT64_MAX

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Specifying 0 in timeout parameter of
ngtcp2_conn_set_keep_alive_timeout is reserved for a future extension, and for now it is treated as if UINT64_MAX is given.
=> Reserve keep-alive timeout 0 as future extension

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Assert ngtcp2_transport_params.max_idle_timeout and max_ack_delay for invalid values.
=> Assert max_idle_timeout and max_ack_delay

lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, tests/ngtcp2_conn_test.c
Include PING in ACK once per RTT if an endpoint only sends non ACK-eliciting packets in this period as suggested by RFC 9000, section 13.2.4.  Previously, we did this once per continuous 3 non-ACK eliciting packets.
=> Include PING in ACK once per RTT

lib/includes/ngtcp2/ngtcp2.h
Initially, we recommended to drop connection without any action on a fatal error (that is liberr < NGTCP2_ERR_FATAL).  But now the general error handling is always call ngtcp2_conn_write_connection_close except for some particular cases.
=> Close connection with fatal error

README.rst
I was able to successfully run ngtcp2 with boringssl a while back.   Checking in the README steps in case it might come in handy!
=> Added borringssl build instructions to README.rst

CMakeLists.txt
Bump minimum cmake version to 3.20 which is the first version that has CMAKE_C_BYTE_ORDER.
=> Bump minimum cmake version to 3.20

doc/source/programmers-guide.rst, examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
ngtcp2_conn_get_num_scid has been removed.  ngtcp2_conn_get_scid(conn, NULL) now returns the number of Source Connection IDs that this function writes to the given buffer.
Similarly, ngtcp2_conn_get_num_active_dcid has been removed, and ngtcp2_conn_get_active_dcid(conn, NULL) returns the number of Destination Connection IDs that this function writes to the given buffer.
=> Rework getting the number of Connection IDs

lib/ngtcp2_conn.c
=> Return NGTCP2_ERR_INVALID_ARGUMENT if a given datagram is too large

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Do not send keep-alive PING in 0-RTT packet.  Those PING frames should be sent in 1-RTT packet after handshake completion.
=> Do not send keep-alive PING in 0-RTT packet

lib/ngtcp2_conn.c
No need to check state because while server is writing handshake packets, it is not in NGTCP2_CS_POST_HANDSHAKE state.
=> No need to check state

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Fix bug that NGTCP2_ERR_STREAM_DATA_BLOCKED is not returned to a calling application when it should be.
Make sure that 0-RTT packet contains PADDING even if it does not have stream data.
=> Fix handling of NGTCP2_ERR_STREAM_DATA_BLOCKED

crypto/picotls/picotls.c
=> picotls: max_early_data_size is of type size_t

lib/ngtcp2_err.c
=> Use NGTCP2_INTERNAL_ERROR for NGTCP2_ERR_HANDSHAKE_TIMEOUT

crypto/boringssl/CMakeLists.txt, crypto/gnutls/CMakeLists.txt, crypto/picotls/CMakeLists.txt, crypto/quictls/CMakeLists.txt, crypto/wolfssl/CMakeLists.txt
Not having the STATIC keyword in `add_library(...)` makes CMake go look for a `BUILD_SHARED_LIBS` variable and, if set, makes the "static" library crypto targets actually create a shared library.
This causes a problem if including ngtcp2 as a subproject from some other project that itself happens to have a default of `BUILD_SHARED_LIBS=ON`, resulting in the "static" targets getting built dynamically.
This fixes it by making the crypto static library targets explicitly STATIC so that this cmake messiness doesn't happen (and also matches the way the main ngtcp2_static target is created).
=> Make crypto static library targets explicitly STATIC

lib/ngtcp2_strm.c
After some re-factorization, now there is no need to check the length of streamfrq because strm_streamfrq_unacked_pop returns empty STREAM frame for a specific case.
=> Simplify ngtcp2_strm_streamfrq_pop

lib/ngtcp2_bbr.c, lib/ngtcp2_bbr2.c, lib/ngtcp2_cc.h, lib/ngtcp2_rtb.c
The largest acknowledged packet that ECN reacts to is the packet referred in largest_ack field, not the largest packet newly acknowledged.
=> Fix ECN largest acked sent time

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
If an empty packet is created because of blocked stream data, NGTCP2_CONN_FLAG_PPE_PENDING might still be set in conn->flags.  That causes assertion failure where NGTCP2_CONN_FLAG_PPE_PENDING is not expected.
Fixes #928
=> Fix assertion failure

crypto/quictls/quictls.c
This change fixes compile errors with libressl.  This is a stopgap solution.  If the difference between libressl and quictls gets larger, we will consider to make a separate library for libressl.
Applications in examples do not compile with libressl, and it is a known fact, and we do not fix it until libressl gets its own ngtcp2_crypto library.
Fixes #935
=> Fix compile error with libressl

lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_log.c, lib/ngtcp2_pkt.c, lib/ngtcp2_pkt.h, lib/ngtcp2_qlog.c, lib/ngtcp2_rtb.c, lib/ngtcp2_rtb.h, lib/ngtcp2_strm.c, lib/ngtcp2_strm.h, tests/ngtcp2_conn_test.c, tests/ngtcp2_pkt_test.c, tests/ngtcp2_qlog_test.c
Share mostly identical lines of code between STREAM and CRYPTO frames by unifying its underlying structures.
=> Merge ngtcp2_crypto into ngtcp2_stream

lib/ngtcp2_log.c, lib/ngtcp2_log.h
Add log event filter to only emit selected events.  This is purely for debugging during library development.
=> Add log event filter

crypto/shared.c
ngtcp2_crypto_verify_retry_token now returns -1 if cil validation fails instead of failing assertion.
=> ngtcp2_crypto_verify_retry_token: Return -1 if cil validation fails

lib/ngtcp2_conn.c, lib/ngtcp2_log.c, lib/ngtcp2_log.h, lib/ngtcp2_rtb.c
Rename NGTCP2_LOG_EVENT_RCV to NGTCP2_LOG_EVENT_LDC because RCV is ambiguous (people might take it as "receive").
=> Rename NGTCP2_LOG_EVENT_RCV to NGTCP2_LOG_EVENT_LDC

crypto/shared.c, lib/ngtcp2_crypto.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conversion_test.c, tests/ngtcp2_crypto_test.c, tests/ngtcp2_test_helper.c
This a fix we had on our side. The remaining of the lib is using `NGTCP2_` prefixed `AF_INET` macros, but this file was not for these two lines.
FYI: We didn't update samples/tests to use the ngtcp2 macros.
=> Fix missing prefix for AF_INET macros in ngtcp2_crypto.c

.github/workflows/build.yml, lib/includes/ngtcp2/ngtcp2.h
Previously, we defined NGTCP2_AF_INET and NGTCP2_AF_INET6 to our chosen values, but they are arbitrary values, and hard to reason about.
With this commit, if NGTCP2_USE_GENERIC_SOCKADDR is defined, NGTCP2_AF_INET and NGHTTP2_AF_INET6 should also be defined externally.
=> Rework how network families are defined with generic sock addr

CMakeLists.txt
Previously these were were included transitively via `cmake/ExtractValidFlags.cmake`. #964 deleted that file. The replacements it added pulled these includes after the local code uses them when `ENABLE_ASAN` enabled.
Re-add these includes into the `CMakeLists.txt` that uses them.
Reported-by: fpliu
Fixes #979
=> cmake: re-add two missing includes

lib/includes/ngtcp2/ngtcp2.h
=> Deprecate NGTCP2_PROTO_VER_MIN and NGTCP2_PROTO_VER_MAX

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Similar convenience API already exists for write_stream
=> ngtcp2_conn_write_datagram conveniently accepts single buffer

lib/ngtcp2_unreachable.h
Use __FILE_NAME__ instead of __FILE__ not to include a full source file path.
Fixes #1003
=> Use __FILE_NAME__ instead of __FILE__

lib/ngtcp2_bbr.c
This commit reverts 1ba4cf1085c47f77d5949338a310c8501a0d16e1 The change is not easy to reason about now.
=> Revert ignoring loss signal during startup

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc
In HTTP without extension, server does not initiate bidirectional streams.  Set those stream limits to 0 by default.  They can be configured via options for testing purposes.
=> examples: Clarify stream limits

docker/Dockerfile
OpenSSL 1.1.1 has been EOLed, and OpenSSL 3.x have various performance issues because of its design decision.  aws-lc is boringssl based TLS stack, and it has a versioned release which hopefully provides API compatibility.
=> docker: Switch to bsslclient and bsslserver

README.rst, examples/Makefile.am, interop/Dockerfile, interop/run_endpoint.sh
Switch interop client/server to wolfssl because OpenSSL 1.1.1 has been EOLed and OpenSSL 3.x has the various performance issues due to its design decision.  wolfssl has been chosen because it has the ability to specify chacha cipher suite and it is also relatively easy to build compared to GnuTLS.
=> interop: Switch to wolfssl

lib/ngtcp2_conn.c, lib/ngtcp2_strm.c, lib/ngtcp2_strm.h, tests/main.c, tests/ngtcp2_strm_test.c, tests/ngtcp2_strm_test.h
- Remove redundant check for NGTCP2_STRM_FLAG_STOP_SENDING.
- Do not buffer reordered data if STOP_SENDING is sent.
=> Optimize STOP_SENDING

examples/util_gnutls.cc
Added include of <algorithm> as this seems to be required when building on recent Arch linux against GCC libc++.
The compiler was complaining about `std::copy_n` not being defined.
=> examples: Add include in GnuTLS example

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Fix assertion failure in a race condition where server is not transitioned to NGTCP2_CS_POST_HANDSHAKE state after handshake is confirmed.
Fixes #1151
=> ngtcp2_conn_write_connection_close: Fix assertion failure

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conn_test.h
This commit adds the following 2 types:
- NGTCP2_CCERR_TYPE_DROP_CONN
- NGTCP2_CCERR_TYPE_RETRY
These are 2 special error codes returned from ngtcp2_conn_read_pkt, and need special handling.  ngtcp2_ccerr_set_liberr is updated to set these types when NGTCP2_ERR_DROP_CONN and NGTCP2_ERR_RETRY are set respectively.
=> Add 2 new ngtcp2_ccerr_type values

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_strm.h, tests/ngtcp2_conn_test.c
Now empty stream data transmission is allowed only when:
- no data, including empty data, has been submitted; or
- NGTCP2_WRITE_STREAM_FLAG_FIN flag is set
It captures the only known use case of empty STREAM frame, that is tell a remote endpoint that a stream is just opened.
=> Rework transmitting empty STREAM frame

crypto/includes/ngtcp2/ngtcp2_crypto.h
Reduce NGTCP2_CRYPTO_TOKEN_RAND_DATALEN to 16 which is large enough.
=> crypto: Reduce NGTCP2_CRYPTO_TOKEN_RAND_DATALEN to 16

examples/h09server.cc, examples/server.cc
QUIC minimum Short packet is 21 bytes, but it does not allow empty payload, thus effectively the shortest packet size is 22 bytes.
=> QUIC min Short packet is 22

CMakeLists.txt, CMakeOptions.txt, lib/CMakeLists.txt
Add a new option `BUILD_TESTING` to control whether or not the library is built with testing. Also fix a library naming conflict when building both static and shared libraries in MSVC by setting a default of `_static` for `STATIC_LIB_SUFFIX`.
=> cmake: add BUILD_TESTING, fix MSVC with static + shared

.github/workflows/build.yml, README.rst, ci/build_wolfssl.sh
This commit adds macos-14 build.  The existing macos-12 is replaced with macos-13.  Bump BoringSSL so that it can be built without Go. Change cache key to include runner name rather than OS name which is shared by macos runners, and different versions of Ubuntu when we upgrade it.
=> ci: Add macos-14

CMakeLists.txt
Add $BUILD_TESTING info to CMake Summary
=> CMakeLists(.txt): Add Build Test info on summary

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Keep-alive packet should trigger PTO to deal with the packet loss.
Fixes #1225
=> Keep-alive packet should trigger PTO

lib/ngtcp2_conn_stat.h, lib/ngtcp2_rtb.c
Fix ngtcp2_conn_stat.max_tx_udp_payload_size update to consider the case where no_tx_udp_payload_size_shaping is enabled.
Fix the document so that ngtcp2_conn_stat.max_tx_udp_payload_size is the maximum UDP payload size for the current path.
=> Fix ngtcp2_conn_stat.max_tx_udp_payload_size update

lib/ngtcp2_acktr.h
Because we create ACK frame with at most NGTCP2_MAX_ACK_RANGES + 1 ranges, including the first range, no need to remember more than those ranges.
=> Adjust NGTCP2_ACKTR_MAX_ENT to match NGTCP2_MAX_ACK_RANGES + 1

lib/ngtcp2_frame_chain.c, lib/ngtcp2_frame_chain.h
Simplify ngtcp2_frame_chain allocation and deallocation for ngtcp2_stream with new macros.
=> Refactor ngtcp2_frame_chain allocation for ngtcp2_stream

examples/tls_client_context_picotls.cc, examples/tls_server_context_picotls.cc
As the variables are excluded for LibreSSL in picotls's [openssl.h](https://github.com/h2o/picotls/blob/master/include/picotls/openssl.h), this patch excludes it by `#if PTLS_OPENSSL_HAVE_*`.
Without this patch, it is not possible to build the examples for picoTLS + libressl.
=> Fix examples for picotls + libressl

lib/ngtcp2_idtr.c, lib/ngtcp2_idtr.h
Clean doc and fix wrong assertions.  The unused ngtcp2_idtr_first_gap is removed.
=> ngtcp2_idtr: Clean doc and fix wrong assertions

lib/CMakeLists.txt, lib/Makefile.am, lib/config.cmake.in
Now is possible to use the command find_package with cmake to find ngtcp2, I've done the same to nghttp3 recently.
=> Added options to command find_package

examples/template.h
This change fixes the following deprecation warning from examples/template.h.
```
third-party/ngtcp2/examples/template.h:63:41: error: identifier '_m' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
63 | constexpr unsigned long long operator"" _m(unsigned long long m) {
|                              ~~~~~~~~~~~^~
|     
```
=> Fix deprecation warning in examples/template.h

lib/ngtcp2_conn.c, lib/ngtcp2_idtr.c, lib/ngtcp2_idtr.h, tests/ngtcp2_idtr_test.c
Remove server field because it is only used in assertion.
=> ngtcp2_idtr: Remove server field

lib/ngtcp2_balloc.c, lib/ngtcp2_balloc.h
Optimize alignment space for 16 bytes boundary malloc.  For 8 bytes boundary, it still waste 8 bytes, but it is better than previous 16 bytes.
=> ngtcp2_balloc: Optimize alignment space for 16 bytes boundary malloc

lib/ngtcp2_map.c
=> ngtcp2_map: Fix bug that psl is not updated when an element is removed

examples/tls_server_context_quictls.cc
This patch fixes a tiny typo in `examples/tls_server_context_quictls.cc`.
=> Fix typo in error log for SSL_CTX_new

.github/workflows/build.yml, README.rst, ci/build_libressl.sh, ci/build_picotls.sh, examples/tls_session_base_quictls.cc
As current CI does not run with LibreSSL, some changes introduces
build failure for LibreSSL and need some fixes like bd5368b.
Hence, this patch adds LibreSSL and Picotls+LibreSSL to CI.
=> Add LibreSSL and Picotls+LibreSSL to CI

lib/ngtcp2_ksl.c
ngtcp2_ksl_node is just needed to be 8 bytes aligned because we do not directly allocate it via ngtcp2_balloc.
=> Adjust the alignment of ngtcp2_ksl_node

lib/ngtcp2_bbr.c, lib/ngtcp2_bbr.h
Remove resetting and remembering values on loss, which is not described in the draft and its effectiveness is suspicious.
=> bbr: Remove resetting and remembering values on loss

lib/ngtcp2_conn.c, lib/ngtcp2_conv.c, lib/ngtcp2_conv.h, lib/ngtcp2_pkt.c, lib/ngtcp2_transport_params.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conv_test.c, tests/ngtcp2_pkt_test.c, tests/ngtcp2_test_helper.c, tests/ngtcp2_transport_params_test.c
- ngtcp2_put_uint16be, ngtcp2_put_uint24be, ngtcp2_put_uint32be, ngtcp2_put_uint48be, and ngtcp2_put_uint64be functions are renamed to ngtcp2_put_uint16, ngtcp2_put_uint24, ngtcp2_put_uint32, ngtcp2_put_uint48, and ngtcp2_put_uint64 respectively.
- The existing ngtcp2_put_uint16be is renamed to ngtcp2_put_uint16
to make consistent with the naming scheme applied to ngtcp2_get_uint* functions.
=> Rename ngtcp2_put_uint* functions

lib/ngtcp2_conn.c, lib/ngtcp2_conv.c, lib/ngtcp2_conv.h, lib/ngtcp2_pkt.c, lib/ngtcp2_transport_params.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conv_test.c, tests/ngtcp2_pkt_test.c, tests/ngtcp2_test_helper.c, tests/ngtcp2_transport_params_test.c
This reverts commit c64a6737fbee50a3d5a95525819e96a244ab7396.
=> Revert "Rename ngtcp2_put_uint* functions"

lib/ngtcp2_conn.h
Remove unused NGTCP2_MAX_RX_INITIAL_CRYPTO_DATA and NGTCP2_MAX_RX_HANDSHAKE_CRYPTO_DATA.
=> Remove unused NGTCP2_MAX_RX_(INITIAL|HANDSHAKE)_CRYPTO_DATA

lib/ngtcp2_rst.c, lib/ngtcp2_rst.h, lib/ngtcp2_rtb.c
This reverts commit 2cab537ce8ec1a4c16a5493a9c03c4a1bb68052b.
=> Revert "ngtcp2_rst: Remove window filter and ineffective next_round_delivered"

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc, examples/util_openssl.cc
Bail out if TLS backend does not allow changing ciphers and ciphers option is used.  Remove AES-128-CCM from default ciphers if libressl is used.
=> examples: Bail out with ciphers option when TLS stack ignores it

lib/ngtcp2_conn.c
Otherwise sender gets stuck if these packets are lost and there is no CWND left.
=> PING bundled with ACK should trigger PTO

lib/ngtcp2_pkt.h
Extend ngtcp2_frame so that ngtcp2_stream has at least additional 3 ngtcp2_vec, totaling 4 slots, which can store HEADERS header, HEADERS payload, DATA header, and DATA payload in the standard sized ngtcp2_frame_chain.
=> Extend ngtcp2_frame

lib/ngtcp2_cc.c, lib/ngtcp2_cc.h
Increase CWND under app limited if connection is CWND limited at least once in this packet-timed round.
=> cubic: Increase CWND under app limited if CWND limited is observed

.clang-format, lib/ngtcp2_acktr.c, lib/ngtcp2_conn.c, lib/ngtcp2_gaptr.c, lib/ngtcp2_ksl.c, lib/ngtcp2_ksl.h, lib/ngtcp2_rob.c, lib/ngtcp2_rtb.c, lib/ngtcp2_strm.c, tests/ngtcp2_ksl_test.c
Introduce ngtcp2_ksl_search to inline ngtcp2_ksl_compar that aims to reduce overhead.
=> Introduce ngtcp2_ksl_search

lib/ngtcp2_conn.c
As TCP Linux does, during slow-start, only enter app-limited when less than half of CWND is used.  Also do not enter app-limited during handshake because we have not that much to send in that state, and it would be nicer to warm up CWND with handshake bytes for the upcoming application traffic.
=> Loosen app-limited condition

lib/ngtcp2_conn.c
The previous value is too conservative and does not work well with auto-tuning.
=> Tweak threshold for max_stream_data and max_data transmission

lib/ngtcp2_conn.c
Do not extend app-limited period so that it does not severely limit CWND.
=> Do not extend app-limited period

lib/ngtcp2_rtb.c
It seems this is an oversight in
cbd6f5815c0c6e8ae8040e1ce255103f3ff3cc6a.  This relevant part of code should have been removed in that commit.  Because this function is only called when Retry packet is received, and PMTUD packet is not sent in this phase, this extra code should not cause any issue.
=> Remove outdated PMTUD probe packet handling when it is lost

lib/ngtcp2_conn.c, lib/ngtcp2_pkt.c, lib/ngtcp2_pkt.h, tests/ngtcp2_pkt_test.c, tests/ngtcp2_rtb_test.c, tests/ngtcp2_test_helper.c
len parameter is always 0 in the production library code.  It is only used in unit tests.  Best to optimize to the production code usage.
=> Remove len parameter from ngtcp2_pkt_hd_init

lib/ngtcp2_conn.c
This reverts commit 1d2c8d53405675bf5cf0c4a47c1d0d8ba7978c88.
See #1457
=> Revert "Do not extend app-limited period"

lib/ngtcp2_gaptr.c
Assert !ngtcp2_ksl_it_end in ngtcp2_gaptr_is_pushed just like we do in the other functions.
=> ngtcp2_gaptr: Assert !ngtcp2_ksl_it_end

lib/CMakeLists.txt, lib/Makefile.am, lib/ngtcp2_cid.c, lib/ngtcp2_cid.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_dcidtr.c, lib/ngtcp2_dcidtr.h, lib/ngtcp2_rtb.c, tests/CMakeLists.txt, tests/Makefile.am, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_dcidtr_test.c, tests/ngtcp2_dcidtr_test.h
Extract code around Destination Connection ID to ngtcp2_dcidtr so that those operations are not cluttered in ngtcp2_conn, and make it much more maintainable and testable.
=> Extract code around Destination Connection ID to ngtcp2_dcidtr

lib/ngtcp2_conn.c
We already limit the amount of data to send under 3x amplification limit, so no need to further punish CWND in this period.
=> Avoid limiting CWND during path validation

fuzz/read_write_pkt.cc
conn_client_validate_transport_params() validates params.version_info.chosen_version by comparing it to conn.negotiated_version. To ensure this validation works correctly, conn.negotiated_version should be set before calling ngtcp2_conn_decode_and_set_remote_transport_params().
=> fuzz: Set negotiated version before setting remote transport params

lib/ngtcp2_conn.c, lib/ngtcp2_dcidtr.c, lib/ngtcp2_dcidtr.h, tests/ngtcp2_conn_test.c, tests/ngtcp2_dcidtr_test.c
ngtcp2_conn_get_active_dcid now always returns 1 if Destination Connection ID is zero length after handshake completion.  Its sequence number is 0.
=> Fix ngtcp2_conn_get_active_dcid for zero-length DCID

fuzz/read_write_pkt.cc, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_rtb.c, lib/ngtcp2_rtb.h, tests/ngtcp2_conn_test.c
Rename persistent_congestion_started_ts to handshake_confirmed_ts, and move it to ngtcp2_conn.
=> Rename persistent_congestion_started_ts to handshake_confirmed_ts

lib/ngtcp2_bbr.c, lib/ngtcp2_conn.c
Implement bbr_is_probing_bw as per
https://github.com/ietf-wg-ccwg/draft-ietf-ccwg-bbr/commit/ec8e965913f5b603296d3f74386eb6000e6de9d4
React to lost packet in startup to avoid completely decimating a completing flow.
=> BBR update

lib/ngtcp2_ksl.c
This reverts commit 13d44affed41b4450e466b90b897a94fe3317056.
=> Revert "ngtcp2_ksl: Remove ineffective ksl_node_set_key"

lib/ngtcp2_conn.c
This lead to fuzzer failures on memory allocation failure.
=> Fix returning wrong variable

lib/ngtcp2_pkt.c
Fix assertion error when writing 0 length DATAGRAM by ngtcp2_conn_write_datagram.
=> Fix assertion error when writing 0 length DATAGRAM

tests/ngtcp2_conn_test.c, tests/ngtcp2_test_helper.c, tests/ngtcp2_test_helper.h
Add ngtcp2_tpe_init_conn_handshake_server to simplify setting up ngtcp2_tpe for handshaking server.
=> tests: Add ngtcp2_tpe_init_conn_handshake_server

examples/tls_session_base_quictls.cc, examples/util_openssl.cc
Use WITH_EXAMPLE_BORINGSSL instead of OPENSSL_IS_BORINGSSL and OPENSSL_IS_AWSLC.
=> Use WITH_EXAMPLE_BORINGSSL

examples/Makefile.am
This should fix #1246.
This patch enabels to build "client"/"server" under examples with BoringSSL on macOS where "libev" is installed via macports.
=> putting important libdir and incdir first

crypto/boringssl/libngtcp2_crypto_boringssl.pc.in, crypto/gnutls/libngtcp2_crypto_gnutls.pc.in, crypto/ossl/libngtcp2_crypto_ossl.pc.in, crypto/quictls/libngtcp2_crypto_quictls.pc.in, crypto/wolfssl/libngtcp2_crypto_wolfssl.pc.in
https://github.com/ngtcp2/ngtcp2/pull/1689#issuecomment-3121481153
=> Use Requires.private because it is needed for static linking

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
For ngtcp2_begin_path_validation and ngtcp2_path_validation, use fallback_path consistently.  old_path might not be a correct word in some situations (e.g., the path validation failure).
=> Use fallback_path consistently

examples/client.cc, examples/h09client.cc, examples/util.h, examples/util_test.cc, examples/util_test.h
Fix Connection ID validation for --dcid and --scid options.  The maximum length of Connection ID should be 20 bytes rather than 18 bytes.
=> examples: Fix Connection ID validation

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Remove max_num_pkts parameter from ngtcp2_conn_write_aggregate_pkt. Application can limit the number of packets to aggregate by adjusting the length of the buffer.
=> ngtcp2_conn_write_aggregate_pkt: Remove max_num_pkts parameter

lib/ngtcp2_bbr.c, lib/ngtcp2_cc.c, lib/ngtcp2_conn.c, lib/ngtcp2_log.c, lib/ngtcp2_log.h, lib/ngtcp2_rtb.c
Do not format string in the library, just pass format and args to the callback, and let an application deal with them.
=> ngtcp2_log: Do not format string

examples/client.cc, examples/client.h, examples/server.cc
Now nghttp3 does not delay the deletion of a stream and nghttp3_stream_close callback invocation, call http_stream_close directly inside ngtcp2_stream_close callback.
=> examples: Simplify close callbacks

lib/ngtcp2_ksl.h
ngtcp2_ksl.h is used from C++ code which requires explicit cast.
=> Revert #1798 partially

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
If ngtcp2_settings.no_tx_udp_payload_size_shaping is nonzero, pad Initial packets to ngtcp2_settings.max_tx_udp_payload_size rather than
1200.  This would help if the initial is large with PQC.  It also enables more packet aggregation (GSO).
Previously, ngtcp2_settings.max_tx_udp_payload_size has no defined minimum.  But we implicitly assume it is at least 1200.  Update documentation and add assertion to reflect this.
=> Initial packets padding with no_tx_udp_payload_size_shaping

lib/ngtcp2_conn.c, lib/ngtcp2_pkt.h, tests/ngtcp2_pkt_test.c
Make ngtcp2_stream.fin of type int so that we do not need any casts from integer operation.  The size of ngtcp2_stream does not change on 64-bit systems.
=> Make ngtcp2_stream.fin of type int

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc
For non-GSO case, limit tx buffer to
ngtcp2_conn_get_max_tx_udp_payload_size which is most likely 1 packet. This helps small queue and bandwidth simulated environment to test congestion controllers for cross traffic because QUIC tends to send too much and causes losses.  This change makes connection slower for other cases, but one cannot expect good performance without GSO in QUIC, so it is fine for now.
=> examples: Limit tx buffer for non-GSO case

lib/ngtcp2_ringbuf.c
Resolves #1810. This PR removes all POPCNT intrinsic usage from the debug-only ispow2 helper in ngtcp2_ringbuf.c, replacing it with the canonical bitwise power-of-two test: n && !(n & (n - 1)). This resolves crashes on CPUs without POPCNT while preserving performance.
•	ispow2 used POPCNT intrinsics under #ifndef NDEBUG.
•	CMakeLists.txt strips -DNDEBUG from Release-like builds, so the code executed everywhere.
•	On CPUs lacking POPCNT, the intrinsic produced an illegal instruction fault.
•	The bitwise formulation is architecture-neutral, constant-time, and emits just a few basic instructions.
•	For a single power-of-two check, POPCNT provides negligible benefit versus its complexity.
•	Avoids runtime CPUID dispatch and platform-specific branches.
•	Eliminates risk of crashes on older or …
=> Replace POPCNT-based ispow2 with portable bitwise implementation to prevent illegal instruction crashes

lib/ngtcp2_bbr.c, lib/ngtcp2_bbr.h, lib/ngtcp2_cc.c, lib/ngtcp2_cc.h, lib/ngtcp2_rtb.c
Pass ngtcp2_cc_ack to CC on_congestion_event so that it can have all information after ACK processing.  Move ECN verification after packet loss detection to achieve it.  This simplifies the congestion event handling in BBR.
=> Pass ngtcp2_cc_ack to CC on_congestion_event
