ngtcp2/ngtcp2

examples/Makefile.am, examples/client.cc, examples/client.h, examples/crypto.cc, examples/crypto.h, examples/debug.cc, examples/server.cc, examples/server.h, lib/Makefile.am, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_conv.c, lib/ngtcp2_conv.h, lib/ngtcp2_crypto.c, lib/ngtcp2_crypto.h, lib/ngtcp2_pkt.c, lib/ngtcp2_pkt.h, lib/ngtcp2_ppe.c, lib/ngtcp2_ppe.h, tests/main.c, tests/ngtcp2_pkt_test.c, tests/ngtcp2_pkt_test.h
=> [WIP] Send CONNECTION_CLOSE in encrypted QUIC packet

examples/debug.cc
=> debug: Display PKN for Packet Number like Wireshark

README.rst, examples/Makefile.am, examples/client.cc, examples/crypto.cc, examples/crypto.h, examples/crypto_boringssl.cc, examples/crypto_openssl.cc, examples/server.cc
This PR adds OpenSSL (master) support.
https://github.com/openssl/openssl/pull/3810 must be applied.
=> Add OpenSSL (master) support

examples/debug.cc
=> debug: Display PKN for Packet Number like Wireshark for short header

README.rst
BoringSSL need golang for build
=> docs: Add note about need golang

lib/Makefile.am, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_range.c, lib/ngtcp2_range.h, lib/ngtcp2_rob.c, lib/ngtcp2_rob.h, tests/Makefile.am, tests/main.c, tests/ngtcp2_range_test.c, tests/ngtcp2_range_test.h, tests/ngtcp2_rob_test.c, tests/ngtcp2_rob_test.h
=> Rewrite reorder buffer

lib/Makefile.am, lib/ngtcp2_acktr.c, lib/ngtcp2_acktr.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, tests/Makefile.am, tests/main.c, tests/ngtcp2_acktr_test.c, tests/ngtcp2_acktr_test.h
=> Re-write ack tracker

examples/debug.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_pkt.c, lib/ngtcp2_pkt.h, tests/main.c, tests/ngtcp2_pkt_test.c, tests/ngtcp2_pkt_test.h
=> Encode and decode all frames

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_upe.c
=> Call callback for outgoing PADDING frame

examples/client.cc, examples/client.h, examples/server.cc, examples/server.h, lib/Makefile.am, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, lib/ngtcp2_map.c, lib/ngtcp2_map.h, lib/ngtcp2_rtb.c, lib/ngtcp2_rtb.h, tests/Makefile.am, tests/ngtcp2_map_test.c, tests/ngtcp2_map_test.h
=> Retransmit lost unprotected frames

examples/client.cc, examples/debug.cc, examples/debug.h, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_crypto.c, tests/Makefile.am, tests/main.c, tests/ngtcp2_crypto_test.c, tests/ngtcp2_crypto_test.h
Send and receive TransportParameters.
=> Transport params

examples/debug.cc
=> debug: num_bl(oc)ks is rename to ACK Block Count with draft-08

.travis.yml
(re) Add macOS builder 
Fix some typo...
=> Enhance travis build

examples/client.cc, examples/server.cc
As NSS and boringssl create the "EXPORTER_SECRET" entry in the key log
file, let's patch OpenSSL too and add keylog callbacks such that these
secrets can be retrieved. The exporter secret can be used with Wireshark
for deriving 1-RTT keys to enable payload decryption.
___
Usage:
Build OpenSSL from https://github.com/Lekensteyn/openssl/tree/tls13-keylog-exporter-secret (which is master + https://github.com/Lekensteyn/openssl/commit/22741b0fb52785d21d0ffb1933f9c1d105170798).
Build this ngtcp2 branch (https://github.com/Lekensteyn/ngtcp2/commits/tls13-exporter-keylog) using that OpenSSL.
~~(I plan to attempt upstreaming these OpenSSL changes as well, but need to add tests first.)~~ Proposed upstream 0-RTT/1-RTT key log: https://github.com/openssl/openssl/pull/5702
Get Wireshark with QUIC …
=> example: Add support for writing TLS key log file

examples/server.cc
It will significant improve the ngtcp2's performance.
=> Drain all udp packet

CMakeLists.txt, appveyor.yml, cmakeconfig.h.in, lib/ngtcp2_conv.c, lib/ngtcp2_crypto.c, lib/ngtcp2_log.c, lib/ngtcp2_map.c, lib/ngtcp2_net.h, lib/ngtcp2_ringbuf.c
The library doesn't build on Windows due to a small number of errors, mostly missing definitions for a few functions.
=> Fix Windows builds

examples/debug.cc, lib/ngtcp2_log.c
#130 rebased onto draft-22 branch
=> Remove final newlines from log messages.

examples/client.cc, examples/client.h, examples/server.cc, examples/server.h
=> Remove redundant Buffer::bufsize()

README.rst
This commit adds information about configuring Wireshark for analyzing
QUIC traffic.
=> Add Wireshark configuration steps

lib/ngtcp2_pkt.c
Refs: https://github.com/ngtcp2/ngtcp2/issues/191
=> Add comment to clarify len in pkt_decode_version_cid

examples/server.cc
The example server uses sendmsg() in blocking mode and NETWORK_ERR_SEND_BLOCKED is never returned as an error.
=> Remove handling of NETWORK_ERR_SEND_BLOCKED in example server

crypto/gnutls/gnutls.c
Reported by Peter Wu in:
https://github.com/curl/curl/pull/5443#issuecomment-633138665
=> gnutls: add stub ngtcp2_crypto_set_local_transport_params

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_addr.c
=> Use winsock.h on windows instead of sys/socket.h

examples/simpleclient.c, examples/tls_client_context_boringssl.cc, examples/tls_client_context_openssl.cc, examples/tls_client_session_boringssl.cc, examples/tls_client_session_openssl.cc, examples/tls_server_context_boringssl.cc, examples/tls_server_context_openssl.cc, examples/tls_server_session_boringssl.cc, examples/tls_server_session_openssl.cc
SSL_CTX_new may be return NULL in low memory case.
=> Check ssl is not null

lib/ngtcp2_conn.c, lib/ngtcp2_qlog.c, lib/ngtcp2_qlog.h
=> Qlog token

examples/client.cc, examples/client.h, examples/h09client.cc, examples/h09client.h
=> client: Deal with EAGAIN/EWOULDBLOCK from sendmsg

lib/ngtcp2_conn.c, lib/ngtcp2_conv.c, lib/ngtcp2_conv.h, lib/ngtcp2_pkt.c, lib/ngtcp2_pkt.h, lib/ngtcp2_ppe.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_pkt_test.c, tests/ngtcp2_test_helper.c
=> Extend Long header Length field to 4 bytes

examples/client.cc, examples/client.h, examples/client_base.h, examples/h09client.cc, examples/h09client.h, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_pkt.h, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conn_test.h
client performs incompatible version negotiation when Version
Negotiation packet is received.
=> client version negotiation

examples/h09server.cc, examples/server.cc, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Add ngtcp2_conn_get_path_max_udp_payload_size to maximize GSO usage.
=> Add ngtcp2_conn_get_path_max_udp_payload_size

lib/ngtcp2_conn.c
=> Set app_error_code even if RESET_STREAM is not going to be sent

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_rtb.c, lib/ngtcp2_strm.c, lib/ngtcp2_strm.h, tests/ngtcp2_conn_test.c
=> Add ngtcp2_conn_get_stream_loss_count

lib/ngtcp2_conn.c
=> Call stream_close before removing stream from map

lib/ngtcp2_conn.c
Amend 2b4ae4d20b9701827f423341dd6d18d9addf23ba
=> Fix memory leak

lib/ngtcp2_cc.c
Incorporate draft-ietf-tcpm-rfc8312bis-09 cwnd calculation.
=> cubic cc enhancement

lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
=> shutdown: Tweak for unidirectional streams

lib/ngtcp2_conn.c
=> Set app_error_code even if STOP_SENDING is not going to be sent

examples/client.cc, examples/h09client.cc
=> Do not enclose numeric IPv4 address with square brackets

.github/workflows/interop.yml
See
https://github.com/docker/login-action/tree/21f251affc0769ccac8a1cf17e937592fb492337#github-container-registry
=> Follow the best practice when authenticating ghcr

.github/workflows/cflite_batch.yaml
=> Revert "fuzzer: Report unreproducible crashes"

lib/ngtcp2_net.h
=> add casts to silence implicit conversion warnings

doc/source/programmers-guide.rst
=> Update Timers section

examples/tls_server_context_openssl.cc
Now OpenSSL server verifies that QUIC version encoded in session ticket equals to the client chosen version.
=> server: Verify QUIC version encoded in session ticket

examples/tls_server_context_picotls.cc
Now picotls server verifies that QUIC version encoded in session ticket equals to the client chosen version.
=> ptlsserver: Verify QUIC version encoded in session ticket

lib/ngtcp2_bbr2.c
=> bbr2: Fix assertion failure

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
=> Fix bug that a remote uni stream never be closed

crypto/shared.c, crypto/shared.h
Adjust version parameter position for the crypto internal functions in a consistent manner.
=> crypto: Adjust version parameter position for the internal functions

crypto/picotls/picotls.c
=> fix compiler error for picotls not supporting chacha20poly1305

lib/ngtcp2_conn.c, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conn_test.h
=> Make DATAGRAM PTO-eliciting

lib/ngtcp2_bbr.c, lib/ngtcp2_bbr2.c
=> bbr: Follow more closely to the draft when setting send_quantum

lib/ngtcp2_pkt.c, tests/main.c, tests/ngtcp2_pkt_test.c, tests/ngtcp2_pkt_test.h
=> Fix bug that stream frame type detection is too relaxed

lib/ngtcp2_conn.c
Update timestamp when ngtcp2_conn_initiate_key_update is called.  Also update timestamp every time ngtcp2_conn_handle_expiry is called.
Refactor the location where conn_update_timestamp is called to remove any duplication.
=> Tweak timestamp update

tests/ngtcp2_conn_test.c
Add a test to make sure that client can send PTO Initial packet even if reduced CWND is less than in-flight bytes which are mostly occupied by 0-RTT packets.
=> Add a test to handshake loss scenarios

examples/shared.cc
Validate netlink sequence number.  Fail if NLM_F_MULTI is set in the response header.  Read ACK because we asked for it.
=> More netlink validation

examples/client.cc, examples/client_base.h, examples/h09client.cc, examples/h09server.cc, examples/server.cc, examples/server_base.h, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, lib/ngtcp2_pkt.c, lib/ngtcp2_pkt.h, lib/ngtcp2_rtb.c, lib/ngtcp2_rtb.h, tests/ngtcp2_pkt_test.c, tests/ngtcp2_rtb_test.c
Allow an application to specify the initial packet number.
=> Configurable initial packet number

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc
=> Amend #848

CMakeLists.txt, configure.ac, crypto/includes/CMakeLists.txt, crypto/quictls/.gitignore, crypto/shared.h
=> Fix ngtcp2_crypto_openssl remnants

configure.ac
This reverts commit 01b20ff6c1257cf59fd7950d0de20a31f17e1450.
=> Revert "Add -Winline"

examples/h09server.cc, examples/h09server.h, examples/server.cc, examples/server.h, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
Define token type in order to verify quic bit a bit more strictly.
=> Define token type

doc/source/programmers-guide.rst
=> Fix version parameter text

examples/client.cc, examples/h09client.cc, examples/h09server.cc, examples/server.cc, examples/util.cc, interop/run_endpoint.sh, lib/includes/ngtcp2/ngtcp2.h, lib/ngtcp2_conn.c
Rename NGTCP2_CC_ALGO_BBR2 to NGTCP2_CC_ALGO_BBR_V2.  Also rename --cc option bbr2 to bbrv2 in client/server.
=> Rename NGTCP2_CC_ALGO_BBR2 to NGTCP2_CC_ALGO_BBR_V2

lib/ngtcp2_ksl.c, lib/ngtcp2_ksl.h, lib/ngtcp2_map.c, lib/ngtcp2_map.h
=> windows: Fix warnings

lib/ngtcp2_rtb.c
=> Fix assertion failure

lib/ngtcp2_conn.c
Simply check packet size is 0 and cwnd utilization for now.
=> Rework app_limited

docker/Dockerfile
This reverts commit 86ac44595b7e3075772cff6e8a41ec748055edc2.
=> Revert "docker: Switch to bsslclient and bsslserver"

lib/ngtcp2_cc.c
=> Assert that _BitScanReverse64 never fail

README.rst, ci/build_wolfssl.sh, docker/Dockerfile, interop/Dockerfile
This reverts commit 12de9607efe5309b671a53b011071beeb0cfc658.
=> Revert "wolfSSL: Disable deprecated signature algorithms"

lib/ngtcp2_window_filter.c, tests/CMakeLists.txt, tests/Makefile.am, tests/main.c, tests/ngtcp2_window_filter_test.c, tests/ngtcp2_window_filter_test.h
Use the invalid value (UINT64_MAX) as a zero value.  Copy the comments from the original source code to clarify the algorithm.
=> Add ngtcp2_window_filter tests

lib/ngtcp2_rtb.c, tests/main.c, tests/ngtcp2_conn_test.c, tests/ngtcp2_conn_test.h
Fixes the bug reported in #1063
=> Fix persistent congestion

examples/h09server.cc, examples/h09server.h, examples/server.cc
This reverts commit 228ff240a5b1c576b77b11933fefc8c772c35e46.
=> Revert "Send RESET_STREAM if stream is reset by client"

lib/ngtcp2_cc.c, tests/ngtcp2_cc_test.c
Adopt "Hacker's Delight" algorithm, fixed by Fabian Giesen: https://gist.github.com/anonymous/729557
=> Rewrite ngtcp2_cbrt

Makefile.am
=> Add missing FindJemalloc.cmake to EXTRA_DIST

examples/h09server.cc, examples/server.cc, examples/server_base.h
=> Pack more QUIC packets on large PMTUD probes

README.rst
=> adding "git submodule" and libev stuff

interop/Dockerfile
Fix interop build failure to use custom endpoint image that uses ubuntu:22.04 base image to gain clang-15.
=> Fix interop

.github/workflows/interop-build.yml
See https://docs.docker.com/build/ci/github-actions/multi-platform/
=> chore: Build multi-platform Docker image during CI

lib/ngtcp2_frame_chain.c, lib/ngtcp2_frame_chain.h, lib/ngtcp2_strm.c, tests/ngtcp2_strm_test.c
=> Fix memory leak when stream datacnt gets below allocation threshold

.github/workflows/build.yml
=> CI: Run pytest for group-c

crypto/quictls/quictls.c
Everywhere else in the file it is OSSL_ENCRYPTION_LEVEL.
=> Use OSSL_ENCRYPTION_LEVEL instead of ssl_encryption_level_t.

crypto/shared.c, lib/ngtcp2_unreachable.c
Improve conditional includes as outlined in #1334
=> Conditional compile improvements

lib/ngtcp2_ringbuf.c
Originally authored by @fcharlie and merged by @tatsuhiro-t as https://github.com/ngtcp2/nghttp3/pull/252/
=> Fix ARM64 __popcnt intrinsics

lib/ngtcp2_rst.c
Fix round counting to be what it suppose to be.  Shorten window filter size because now it is too long.  Now always update window filter.
=> ngtcp2_rst: Fix round counting

lib/ngtcp2_rst.c, lib/ngtcp2_rst.h, lib/ngtcp2_rtb.c
Remove window filter again.  Wait and see how this affects performance in cross traffic.
=> ngtcp2_rst: Remove window filter

fuzz/read_write_pkt.cc
This increases the coverage of the fuzzer significantly.
=> Fuzz sequences of different received packets

examples/server.cc
=> examples: Remove unnecessary http-parser include

crypto/picotls/picotls.c
=> picotls: Reset AEAD IV on decryption failure

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
This reverts commit 3b2ef2c48414ece42a0efd56b243ca82131afb5c.
=> Revert "Avoid buffering padding bytes"

lib/ngtcp2_conn.c, lib/ngtcp2_conn.h
Adjust pacing timer for the amount of time that a sender waits too long.
=> Adjust pacing timer

lib/ngtcp2_conn.c, tests/ngtcp2_conn_test.c
- Just check the local address when deciding to accept a packet form different path.
- Remove client disable_active_migration check because it is not much interesting and is not worth checking more.
=> Tweak disable_active_migration

fuzz/read_write_pkt.cc
Restructure read_write_pkt to make exiting loop easier.
=> fuzz: Restructure read_write_pkt

tests/ngtcp2_conn_test.c
Call ngtcp2_conn_set_remote_params so that all assumptions regarding the remote transport parameters are fulfilled.
=> tests: Call ngtcp2_conn_set_remote_params

lib/ngtcp2_conn.c, lib/ngtcp2_conn.h, tests/ngtcp2_conn_test.c
Remember validated path and skip path validation if new path has been validated recently.
=> Remember validated path

examples/util.cc, examples/util.h, examples/util_test.cc
=> examples: Refactor siphash key generation

examples/shared.cc
It seems that IP_PMTUDISC_PROBE works in some advertent situations.
Fixes #1684
=> examples: Adopt IP_PMTUDISC_PROBE

.github/workflows/quic-interop-runner.yml
Run quic-interop-runner in this repository because official one has been unstable quite a while.
=> Run quic-interop-runner

lib/ngtcp2_bbr.c
Previously, ngtcp2_rs conn->rst->rs is modified when a packet is lost. But this is a bit strange, and it is the only place we do in BBR. This change uses new temporary variable ngtcp2_rs on packet loss without modifying the existing conn->rst->rs.  With this change, we observed improvements in the cross traffic test in quic-interop-runner.
=> bbr: Avoid modifying ngtcp2_rs on packet loss
